### ISSUE TITLE
Another package that might interest you

### ISSUE THREAD

**Issue by vdavid** [sambarnes90/node-mautic#3]
Hey @sambarnes90 

I've just finished a bit more up-to-date and more complete Node.js package for Mautic: https://github.com/vdavid/node-mautic

I've started from your code base (I did a bunch of replaces to reformat the API call functions) so I'd like to thank you for your work! Sorry for not forking the repo, I didn't originally intend to publish my package, I've created it for my company, but then I thought, why not, it might be helpful for others too.

If you think my package might help people, please consider recommending it in your README.md so that they have an easier time finding (and perhaps contributing to) it.

Thanks :)
David

**Comment by sambarnes90** [comment]
Great thanks David.

Nice work on your part too!

**Comment by vdavid** [comment]
Thanks, and I appreciate the link you added. :)
